### PR TITLE
fix the memory leak

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
This commit eliminates legacy structs, `ABTI_elem`, `ABTI_contn`, and `ABTI_xstream_contn` from Argobots.  This patch, as a result, solves the memory leak issue reported in #6 and #119; ES's `ABTI_elem` was not only created but not freed (see `src/stream.c`).

### CODE REVIEW

**Comment by shintaro-iwasaki** [comment]
test:jenkins

**Comment by roblatham00** [comment]
If you are sure that no users rely on ABTI_elem, ABTI_contn, or ABTI_xstream_contn, then great. (given the names, I guess they are internal routines so end-users using them get what they deserve).

**Comment by shintaro-iwasaki** [comment]
@roblatham00 You're right. They are internal objects, so no users can access them.

**Comment by roblatham00** [comment]
:+1:   ship it!

**Pull request merged**
